steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'configure-docker', '${_CONT_REGISTRY_NAME}']

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t',
    '${_CONT_REGISTRY_NAME}/${_PROJECT_ID}/${_CONT_REPOSITORY_NAME}/${_CONT_IMAGE_NAME}:latest',
    '--cache-from',
    '${_CONT_REGISTRY_NAME}/${_PROJECT_ID}/${_CONT_REPOSITORY_NAME}/${_CONT_IMAGE_NAME}:latest',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_CONT_REGISTRY_NAME}/${_PROJECT_ID}/${_CONT_REPOSITORY_NAME}/${_CONT_IMAGE_NAME}:latest']


- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 
    'deploy', 
    '${_CONT_IMAGE_NAME}',
    '--image', '${_CONT_REGISTRY_NAME}/${_PROJECT_ID}/${_CONT_REPOSITORY_NAME}/${_CONT_IMAGE_NAME}:latest',
    '--service-account', '${_SERVICE_ACCOUNT}',
    '--project', '${_PROJECT_ID}',
    '--region', '${_REGION}',
    '--vpc-connector', '${_VPC_CONNECTOR}',
    '--memory', '${_MEMORY}',
    '--cpu', '${_CPU}',
    '--concurrency','${_CONCURRENCY}',
    '--timeout', '${_TIMEOUT}',
    '--allow-unauthenticated'
  ]

images: ['${_CONT_REGISTRY_NAME}/${_PROJECT_ID}/${_CONT_REPOSITORY_NAME}/${_CONT_IMAGE_NAME}:latest']
options:
  logging: CLOUD_LOGGING_ONLY